config/routes.rb
Ardhivie::Application.routes.draw do

  devise_for :users
  resources :ufiles, :except => :index
  resources :locations do
    resources :ufiles, :only => :index
  end
  
  match "/download/ufile/:id" => "download#ufile", :as => :download_ufile
  
  namespace :api do
    root :to => "home#index"
    resources :ufiles, :except => :index
    resources :locations do
      collection do
        get :mine
      end
      resources :ufiles, :only => :index
    end
  end

  # You can have the root of your site routed with "root"
  # just remember todelete public/index.html.
  root :to => 'home#index'
  get "pages/home"
  get "pages/contact"
  get "pages/aboutus"
  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :latitude, :longitude, :user_id, :address, :title
  belongs_to :user
  has_many :ufiles
  
  validates :latitude, :longitude, :title, :presence => true  
end

app/models/ufile.rb
class Ufile < ActiveRecord::Base
  include Rails.application.routes.url_helpers
  attr_accessible :name, :data, :location_id
  has_attached_file :data, 
    :styles => { :medium => "300x300>", :thumb => "100x100>", :tiny => "10x10>" },
    :storage => :s3,
    :s3_credentials => "#{Rails.root}/config/s3.yml",
    :s3_permissions => :private,
    :path => ":rails_env/:class/:attachment/:style/:id/:filename"
  belongs_to :user
  belongs_to :location
  
  # validates :name, :location_id, :presence => true
  before_post_process :image?

  def image?
    !(data_content_type =~ /^image/).nil?
  end

  def to_jq_upload
    {
      "name" => data_file_name,
      "size" => data.size,
      "url" => download_ufile_path(id) ,
      "thumbnail_url" => image? ? data.url(:tiny) : nil,
      "delete_url" => api_ufile_path(self),
      "delete_type" => "DELETE"
    }
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable#, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  
  has_many :locations
  has_many :ufiles
  has_many :invitations, :class_name => 'User', :as => :invited_by
  
  def sign_up_at
    !invitation_accepted_at.blank? && invitation_accepted_at > created_at ? invitation_accepted_at : created_at
  end
  
  def user_ids_in_network
    [id, invited_by_id] + invitation_ids
  end
end

app/controllers/api/application_controller.rb
class Api::ApplicationController < ApplicationController
  respond_to :json
end

app/controllers/api/home_controller.rb
class Api::HomeController < Api::ApplicationController
  def index
    respond_with({:status => :ok})
  end
end

app/controllers/api/locations_controller.rb
class Api::LocationsController < Api::ApplicationController
  def index
    @locations = Location.where(:user_id => current_user.user_ids_in_network)
    respond_with(@locations)
  end
  
  def mine
    @locations = current_user.locations.all
    respond_with(@locations)
  end

  def show
    respond_with(Location.find(params[:id]))
  end

  def create
    @location = Location.new params[:location]
    @location.user = current_user
    if @location.save
      respond_with(@location)
    else
      respond_with(@location, status: :unprocessable_entity)
    end
  end

  # PUT /locations/1
  # PUT /locations/1.json
  def update
    @location = Location.find(params[:id])

    respond_to do |format|
      if @location.update_attributes(params[:location])
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location = Location.find(params[:id])
    @location.destroy
    respond_with(:no_content)
  end
end

app/controllers/api/ufiles_controller.rb
class Api::UfilesController < Api::ApplicationController
  def index
    @ufiles = Ufile.where(:location_id => params[:location_id]).order("id DESC").all
    respond_with(@ufiles.map{|x| x.to_jq_upload }.to_json)
  end
  
  def show
    respond_with(Ufile.find(params[:id]))
  end

  def create
    @ufile = Ufile.new params[:ufile]
    if @ufile.save
      render json: [@ufile.to_jq_upload].to_json
    else
      respond_with(@ufile, status: :unprocessable_entity)
    end
  end

  def update
    @ufile = Ufile.find(params[:id])

    respond_to do |format|
      if @ufile.update_attributes(params[:ufile])
        format.html { redirect_to @ufile, notice: 'Ufile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ufile.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @ufile = Ufile.find(params[:id])
    @ufile.destroy
    respond_with(:no_content)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery
  before_filter :authenticate_user!
  layout :layout_by_resource

  protected

  def layout_by_resource
    if user_signed_in?
      "application"
    else
      "login"
    end
  end
end

app/controllers/download_controller.rb
class DownloadController < ApplicationController
  def ufile
    redirect_to Ufile.find(params[:id]).data.expiring_url(10)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  # GET /locations
  # GET /locations.json
  def index
    @locations = current_user.locations.all
   respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @locations }
    end
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
    @location = Location.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/new
  # GET /locations/new.json
  def new
    @location = Location.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/1/edit
  def edit
    @location = Location.find(params[:id])
  end

  # POST /locations
  # POST /locations.json
  def create
   @user = User.find(current_user.id)
   @location = @user.locations.create!(:latitude => params[:latitude], :longitude => params[:longitude])

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render json: @location, status: :created, location: @location }
      else
        format.html { render action: "new" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /locations/1
  # PUT /locations/1.json
  def update
    @location = Location.find(params[:id])

    respond_to do |format|
      if @location.update_attributes(params[:location])
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location = Location.find(params[:id])
    @location.destroy if current_user.id == @location.user_id

    respond_to do |format|
      format.html { redirect_to locations_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def contact
  end

  def aboutus
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/ufiles_helper.rb
module UfilesHelper
end

app/views/data/_form.html.erb
<%= form_for(@datum) do |f| %>
  <% if @datum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@datum.errors.count, "error") %> prohibited this datum from being saved:</h2>

      <ul>
      <% @datum.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/home/_modal.html.slim
#new-location-form.modal.hide.fade tabindex="-1" role="dialog" aria-labelledby="modal-label" aria-hidden="true" data-show="false"
  .modal-header
    button type="button" class="close" data-dismiss="modal" aria-hidden="true" &times;
    h3 id="modal-label" New Location
    p
      span class="label label-important" Please Note:
      '   This new location you create will be viewable by all your shared collaborators on ArdhiView.
  .modal-body
    .alert.alert-block.alert-error.hide
      a.close.close-alert-message href="#" data-dismiss="location-error" &times;
      p.alert-message Location could not be saved!
    = simple_form_for Location.new, :url => api_locations_path do |form|
      = form.input :title
      = form.input :address
      = form.input :latitude, :as => :hidden
      = form.input :longitude, :as => :hidden
  .modal-footer
    .pull-left.location-information
      i.icon.icon-map-marker
      |  latitude: 
      span.location-display-lat
      | , longitude: 
      span.location-display-lng
    button.btn data-dismiss="modal" aria-hidden="true" Cancel
    button.btn.btn-primary.save-new-location Save Location

app/views/home/_template.html.erb
<script id="template-upload" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-upload fade">
        <td class="name"><span>{%=file.name%}</span></td>
        <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
        {% if (file.error) { %}
            <td class="error"><span class="label label-important">{%=locale.fileupload.error%}</span> {%=locale.fileupload.errors[file.error] || file.error%}</td>
        {% } else if (o.files.valid && !i) { %}
            <td>
                <div class="progress progress-success progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><div class="bar" style="width:0%;"></div></div>
            </td>
        {% } %}
    </tr>
{% } %}
</script>
<!-- The template to display files available for download -->
<script id="template-download" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-download fade">
        {% if (file.error) { %}
            <td class="error" colspan="2"><span class="label label-important">{%=locale.fileupload.error%}</span> {%=locale.fileupload.errors[file.error] || file.error%}</td>
        {% } else { %}
            <td class="name">
                <a href="{%=file.url%}" title="{%=file.name%}" rel="{%=file.thumbnail_url&&'gallery'%}" download="{%=file.name%}">{%=file.name%}</a>
            </td>
            <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
        {% } %}
        <td class="delete">
            <button class="btn btn-danger" data-type="{%=file.delete_type%}" data-url="{%=file.delete_url%}">
                <i class="icon-trash icon-white"></i>
                <span>{%=locale.fileupload.destroy%}</span>
            </button>
        </td>
    </tr>
{% } %}
</script>
<script id="template-ufile-form" type="text/x-tmpl">
<div class="file-upload-container">
  <form action="/api/ufiles.json" class="fileupload fileupload-{%=o.location_id%}" enctype="multipart/form-data" method="POST" id="form-{%=o.location_id%}">
    <div class="header">
      <h5>{%=o.title%}</h5>
      <p class="lead">{%=o.address%}</p>
    </div>
    <div class="existing-files">
      <table class="table table-striped" role="presentation">
        <tbody class="files">
        </tbody>
      </tbody>
      </table>
    </div>
    <div class="fileupload-buttonbar">
      <div>
        <span class="btn btn-success fileinput-button">
          <i class="icon-plus icon-white"></i>
          <span> Add files... </span>
          <input multiple="multiple" name="ufile[data]" type="file">
          <input class="location_id" name="ufile[location_id]" type="hidden" value="{%=o.location_id%}">
        </span>
        <span class="pull-right">
          <span class="btn btn-primary zoomin-button" data-location-id="{%=o.location_id%}">
            <i class="icon-zoom-in icon-white"></i>
            <span> Zoom In </span>
          </span>
          <span class="btn btn-danger delete-location" data-location-id="{%=o.location_id%}">
            <i class="icon-trash icon-white"></i>
            <span> Delete Location </span>
          </span>
        </span>
      </div>
    </div>
  </form>
</div>
</script>

app/views/home/_upload.html.slim
.file-upload-container
  form class="" action="/ufiles" method="POST" enctype="multipart/form-data"
    .fileupload-buttonbar
      div
        span class="btn btn-success fileinput-button"
          i class="icon-plus icon-white"
          span 
            '  Add files...
          input type="file" name="ufile[data]" multiple="multiple"
          input type="hidden" name="ufile[location_id]" class="location_id"
    .existing-files
      table role="presentation" class="table table-striped"
        tbody class="files"

app/views/home/index.html.slim
#search-section.lead.row-fluid
  .span12
    .control-group
      .controls
        .input-prepend
          span.add-on
            i.icon-search
          input type="text" name="search" id="search"
#message.row-fluid.hide
  .span12
    .alert.alert-block.alert-error
      a.close.close-alert-message href="#" &times;
      h4.alert-heading Oh snap! You got an error!
      p.alert-message Alert Message
.row-fluid
  .span12
    #bookmarks-sidebar.pull-left
      p class="lead"
        ' Your Locations
        = button_tag :class => "btn btn-mini btn-close-bookmark pull-right" do
          i.icon-bookmark
          '  Close Bookmarks
      .bookmarks
        .bookmark
          table.table.table-striped
            thead
              tr
                th Title
                th Address
            tbody
    #google-map.pull-right
= render :partial => "template"
= render :partial => "modal"
= hidden_field_tag :current_user_id, current_user.id

app/views/layouts/application.html.slim
doctype html
html
  head
    title Ardhiview
    meta name="keywords" content="ardhivie"
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = javascript_include_tag "http://maps.google.com/maps/api/js?sensor=true"
    = javascript_include_tag "http://google-maps-utility-library-v3.googlecode.com/svn/trunk/markerclusterer/src/markerclusterer_compiled.js"
    = javascript_include_tag "http://google-maps-utility-library-v3.googlecode.com/svn/trunk/infobubble/src/infobubble-compiled.js"
    = favicon_link_tag "/favicon.ico"
    = csrf_meta_tags
  body
    - if user_signed_in?
      #header
        .navbar.navbar-static-top
          .navbar-inner.container-fluid
            = link_to "Ardhivie", root_path, :class => "brand", :id => "logo"
            ul.nav.pull-right
              li= link_to "My Locations", "#", :class => "my-locations-link", :style => 'display:none;'
              li= link_to "Invite Others", new_user_invitation_path
              li= link_to "My Account", edit_user_registration_path
              li= link_to "Log Out", destroy_user_session_path, :method => :delete
    #content.hide
      .container-fluid    
        - flash.each do |name, msg|
          div class="alert alert-#{name}"
            button type="button" class="close" data-dismiss="alert" ×
            = msg
        = yield
    - if user_signed_in?
      = render :partial => "shared/intercom"

app/views/layouts/login.html.slim
doctype html
html
  head
    title Ardhiview
    meta name="keywords" content="ardhivie"
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = javascript_include_tag "http://maps.google.com/maps/api/js?sensor=true"
    = javascript_include_tag "http://google-maps-utility-library-v3.googlecode.com/svn/trunk/markerclusterer/src/markerclusterer_compiled.js"
    = javascript_include_tag "http://google-maps-utility-library-v3.googlecode.com/svn/trunk/infobubble/src/infobubble-compiled.js"
    = favicon_link_tag "/favicon.ico"
    = csrf_meta_tags
  body#devise
    #content
      .container
        - flash.each do |name, msg|
          div class="alert alert-#{name}"
            button type="button" class="close" data-dismiss="alert" ×
            = msg
        = yield
    - if user_signed_in?
      = render :partial => "shared/intercom"

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<h1>Listing locations</h1>

<table>
  <tr>
    <th>Latitude</th>
    <th>Longitude</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @locations.each do |location| %>
  <tr>
    <td><%= location.latitude %></td>
    <td><%= location.longitude %></td>
    <td><%= location.user_id %></td>
    <td><%= link_to 'Show', location %></td>
    <td><%= link_to 'Edit', edit_location_path(location) %></td>
    <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Location', new_location_path %>

app/views/locations/new.html.erb
<h1>New location</h1>

<%= render 'form' %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Latitude:</b>
  <%= @location.latitude %>
</p>

<p>
  <b>Longitude:</b>
  <%= @location.longitude %>
</p>

<p>
  <b>User:</b>
  <%= @location.user_id %>
</p>


<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>

app/views/pages/aboutus.html.erb
<h1>Pages#aboutus</h1>
<p>Find me in app/views/pages/aboutus.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<!--

<h1>Ardhiview</h1>
<h4>Welcome to Ardhiview. C://The world</h4> 
<p>You are seeing this page because you are signed in! </p> 

-->


<% if user_signed_in? %>
<div id="map" onload="initialize();">
</div>

<% else %>
  <%= link_to "sign in", new_user_session_path %>
<div id='main-image'>
<img src='assets/ardi_logo.jpeg' width="550" height="350" /></div>
<h1 id='home-heading'><%= link_to "Sign up", new_user_registration_path %></h1> 
<% end %>

app/views/shared/_intercom.html.erb
<a id="IntercomTab" href="#">Feedback</a>
<script id="IntercomSettingsScriptTag">
  var intercomSettings = {
    app_id: 'j0sspiv3',
    email: '<%= current_user.email %>', 
    created_at: <%= current_user.sign_up_at.to_i %>,
    widget: {
      activator: '#IntercomTab'
    }
  };
</script>
<script>
  (function() {
    function async_load() {
      var s = document.createElement('script');
      s.type = 'text/javascript'; s.async = true;
      s.src = 'https://api.intercom.io/api/js/library.js';
      var x = document.getElementsByTagName('script')[0];
      x.parentNode.insertBefore(s, x);
    }
    if (window.attachEvent) {
      window.attachEvent('onload', async_load);
    } else {
      window.addEventListener('load', async_load, false);
    }
  })();
</script>

app/views/ufiles/_form.html.slim
= simple_form_for @ufile, :html => { :multipart => true } do |f|
  = f.input :name
  = f.input :data
  = f.button :submit

app/views/ufiles/edit.html.erb
<h1>Editing ufile</h1>

<%= render 'form' %>

<%= link_to 'Show', @ufile %> |
<%= link_to 'Back', ufiles_path %>

app/views/ufiles/index.html.erb
<h1>Listing ufiles</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ufiles.each do |ufile| %>
  <tr>
    <td><%= ufile.name %></td>
    <td><%= link_to 'Show', ufile %></td>
    <td><%= link_to 'Edit', edit_ufile_path(ufile) %></td>
    <td><%= link_to 'Destroy', ufile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Ufile', new_ufile_path %>

app/views/ufiles/new.html.erb
<h1>New ufile</h1>

<%= render 'form' %>

<%= link_to 'Back', ufiles_path %>

app/views/ufiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @ufile.name %>
<%= image_tag @ufile.data.url %>
</p>


<%= link_to 'Edit', edit_ufile_path(@ufile) %> |
<%= link_to 'Back', ufiles_path %>